cc = gcc
deps = Lab5_fun.h Lab5_run.h Lab5_data.h
dc = Lab5.c Lab5_run.c Lab5_fun.c

Lab5: $(dc) $(deps)
	$(cc) $(dc) -o Lab5
clean:
	rm -f *.o
love:
	$(cc) $(dc) -o Lab5 -g
4:
	gcc -o Lab4 Lab4.c Lab4_fun.c Lab4_run.c