cc = gcc
deps = Lab7_data.h Lab7_getStatus.h Lab7_main.h Lab7_nextStatus.h Lab7_input.h Lab7_resList.h Lab7_serList.h
dc = Lab7.c Lab7_main.c Lab7_input.c Lab7_getStatus.c Lab7_nextStatus.c Lab7_resList.c Lab7_serList.c

Lab7: $(dc) $(deps)
	$(cc) $(dc) -o Lab7
clean:
	rm -f *.o
love:
	$(cc) $(dc) -o Lab7 -g